[lightning]
level = "info"
file = "../stage/tidb-lightning-universe.log"
table-concurrency = 1
index-concurrency = 1
region-concurrency = 1
io-concurrency = 1
max-error = 0
task-info-schema-name = "lightning_task_info"
meta-schema-name = "lightning_metadata"

[checkpoint]
enable = true
driver = "file"
dsn = "/tmp/tidb_lightning_checkpoint_p2.pb"

[tikv-importer]
backend = "local"
incremental-import = true
sorted-kv-dir = "../stage/sorted-kv-dir-p2"

[mydumper]
data-source-dir = "./misc/planets-csv-large-2"
filter = ['*.*', '!mysql.*', '!sys.*', '!INFORMATION_SCHEMA.*', '!PERFORMANCE_SCHEMA.*', '!METRICS_SCHEMA.*', '!INSPECTION_SCHEMA.*']
strict-format = true

[mydumper.csv]
separator = ','
delimiter = '"'
terminator = ''
header = true
not-null = false
null = '\N'
backslash-escape = true
trim-last-separator = false

[tidb]
host = "127.0.0.1"
port = 4000
user = "root"
password = ""
status-port = 10080
pd-addr = "127.0.0.1:2379"